### ISSUE TITLE
you cannot pass it just a file it needs a path

### ISSUE THREAD

**Issue by koaning** [godatadriven/asekuro#7]
```
(venv) ➜  01-streaming-algorithms git:(timeseries-nuon-revamp) ✗asekuro test 01-01-introduction-streaming.ipynb 
2018-07-31 13:50:02,183 [commandline.py:test_notebook:113] DEBUG - about to test 01-01-introduction-streaming.ipynb
2018-07-31 13:50:02,183 [commandline.py:_cwd:24] DEBUG - directory of script calling /Users/vincentwarmerdam/Development/accelerator/lecture09_timeseries/lecture/01-streaming-algorithms
Traceback (most recent call last):
  File "/Users/vincentwarmerdam/Development/accelerator/venv/bin/asekuro", line 11, in <module>
    sys.exit(main())
  File "/Users/vincentwarmerdam/Development/accelerator/venv/lib/python3.6/site-packages/asekuro/commandline.py", line 129, in main
    'clean': clean_notebook
  File "/Users/vincentwarmerdam/Development/accelerator/venv/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/Users/vincentwarmerdam/Development/accelerator/venv/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/Users/vincentwarmerdam/Development/accelerator/venv/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/Users/vincentwarmerdam/Development/accelerator/venv/lib/python3.6/site-packages/asekuro/commandline.py", line 114, in test_notebook
    folder, filename = _cwd(nbpath)
  File "/Users/vincentwarmerdam/Development/accelerator/venv/lib/python3.6/site-packages/asekuro/commandline.py", line 27, in _cwd
    os.chdir(folder)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by koaning** [comment]
fixed in https://github.com/godatadriven/asekuro/pull/13
